/*
 * adder-c-fmu — FMI 3.0 Co-Simulation FMU in pure C.
 *
 * Variables
 * ---------
 *  VR 0  time      independent  Float64  Independent time variable
 *  VR 1  input_a   input        Float64  First addend
 *  VR 2  input_b   input        Float64  Second addend
 *  VR 3  sum       output       Float64  sum = input_a + input_b
 *
 * Bindings generated by wit-bindgen from wit/world.wit (co-simulation-fmu world).
 */

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* ── Resource struct definition ──────────────────────────────────────────────
 * The generated header forward-declares this struct as an opaque type; we
 * complete it here before including the header.
 */
struct exports_fmi_fmi3_co_simulation_co_simulation_instance_t {
    bool   in_initialization_mode;
    double current_time;
    double input_a;
    double input_b;
    double output_sum;
};

#include "co_simulation_fmu.h"

/* ── Value-reference assignments ─────────────────────────────────────────── */
#define VR_TIME       0u
#define VR_INPUT_A    1u
#define VR_INPUT_B    2u
#define VR_OUTPUT_SUM 3u

/* ── Version string ──────────────────────────────────────────────────────── */
static const char VERSION_STRING[] = "3.0";

/* ═══════════════════════════════════════════════════════════════════════════
 * common interface
 * ═══════════════════════════════════════════════════════════════════════════ */

void exports_fmi_fmi3_common_get_version(co_simulation_fmu_string_t *ret)
{
    size_t len = sizeof(VERSION_STRING) - 1;
    uint8_t *buf = (uint8_t *)malloc(len);
    memcpy(buf, VERSION_STRING, len);
    ret->ptr = buf;
    ret->len = len;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * co-simulation interface — resource lifecycle
 * ═══════════════════════════════════════════════════════════════════════════ */

bool exports_fmi_fmi3_co_simulation_static_co_simulation_instance_instantiate_co_simulation(
    co_simulation_fmu_string_t  *instance_name,
    co_simulation_fmu_string_t  *instantiation_token,
    co_simulation_fmu_string_t  *resource_path,
    bool visible,
    bool logging_on,
    bool event_mode_used,
    bool early_return_allowed,
    co_simulation_fmu_list_value_reference_t *required_intermediate_variables,
    exports_fmi_fmi3_co_simulation_own_co_simulation_instance_t *ret)
{
    (void)instance_name;
    (void)instantiation_token;
    (void)resource_path;
    (void)visible;
    (void)logging_on;
    (void)event_mode_used;
    (void)early_return_allowed;
    (void)required_intermediate_variables;

    exports_fmi_fmi3_co_simulation_co_simulation_instance_t *inst =
        (exports_fmi_fmi3_co_simulation_co_simulation_instance_t *)
        calloc(1, sizeof(exports_fmi_fmi3_co_simulation_co_simulation_instance_t));
    if (!inst) {
        return false;
    }

    *ret = exports_fmi_fmi3_co_simulation_co_simulation_instance_new(inst);
    return true;
}

/* Called by the runtime when the resource handle is dropped. */
void exports_fmi_fmi3_co_simulation_co_simulation_instance_destructor(
    exports_fmi_fmi3_co_simulation_co_simulation_instance_t *rep)
{
    free(rep);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * co-simulation interface — lifecycle methods
 * ═══════════════════════════════════════════════════════════════════════════ */

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_debug_logging(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    bool logging_on,
    co_simulation_fmu_list_string_t *categories)
{
    (void)self; (void)logging_on; (void)categories;
    return FMI_FMI3_TYPES_STATUS_OK;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_enter_initialization_mode(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    double *maybe_tolerance,
    double start_time,
    double *maybe_stop_time)
{
    (void)maybe_tolerance; (void)start_time; (void)maybe_stop_time;
    self->in_initialization_mode = true;
    return FMI_FMI3_TYPES_STATUS_OK;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_exit_initialization_mode(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self)
{
    self->in_initialization_mode = false;
    return FMI_FMI3_TYPES_STATUS_OK;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_enter_event_mode(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self)
{
    (void)self;
    return FMI_FMI3_TYPES_STATUS_ERROR;
}

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_update_discrete_states(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    exports_fmi_fmi3_co_simulation_discrete_states_info_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{
    (void)self; (void)ret;
    *err = FMI_FMI3_TYPES_STATUS_ERROR;
    return false;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_terminate(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self)
{
    (void)self;
    return FMI_FMI3_TYPES_STATUS_OK;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_reset(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self)
{
    self->in_initialization_mode = false;
    self->current_time  = 0.0;
    self->input_a       = 0.0;
    self->input_b       = 0.0;
    self->output_sum    = 0.0;
    return FMI_FMI3_TYPES_STATUS_OK;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_enter_configuration_mode(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self)
{
    (void)self;
    return FMI_FMI3_TYPES_STATUS_ERROR;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_exit_configuration_mode(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self)
{
    (void)self;
    return FMI_FMI3_TYPES_STATUS_ERROR;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * co-simulation interface — Float64 getter / setter
 * ═══════════════════════════════════════════════════════════════════════════ */

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_float64(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *value_references,
    co_simulation_fmu_list_f64_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{
    size_t n = value_references->len;
    double *buf = (double *)malloc(n * sizeof(double));
    if (!buf) { *err = FMI_FMI3_TYPES_STATUS_ERROR; return false; }

    for (size_t i = 0; i < n; i++) {
        uint32_t vr = value_references->ptr[i];
        switch (vr) {
            case VR_TIME:       buf[i] = self->current_time; break;
            case VR_INPUT_A:    buf[i] = self->input_a;      break;
            case VR_INPUT_B:    buf[i] = self->input_b;      break;
            case VR_OUTPUT_SUM: buf[i] = self->output_sum;   break;
            default:
                free(buf);
                *err = FMI_FMI3_TYPES_STATUS_ERROR;
                return false;
        }
    }
    ret->ptr = buf;
    ret->len = n;
    return true;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_float64(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *value_references,
    co_simulation_fmu_list_f64_t *values)
{
    if (value_references->len != values->len) return FMI_FMI3_TYPES_STATUS_ERROR;

    for (size_t i = 0; i < value_references->len; i++) {
        uint32_t vr  = value_references->ptr[i];
        double   val = values->ptr[i];
        switch (vr) {
            case VR_INPUT_A: self->input_a = val; break;
            case VR_INPUT_B: self->input_b = val; break;
            default: return FMI_FMI3_TYPES_STATUS_ERROR;
        }
    }

    /* Recompute output immediately when in initialization mode. */
    if (self->in_initialization_mode) {
        self->output_sum = self->input_a + self->input_b;
    }
    return FMI_FMI3_TYPES_STATUS_OK;
}

/* ── All other typed getters — not supported ─────────────────────────────── */

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_float32(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_f32_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_int8(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_s8_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_int16(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_s16_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_int32(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_s32_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_int64(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_s64_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_uint8(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_u8_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_uint16(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_u16_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_uint32(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_u32_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_uint64(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_u64_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_boolean(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_bool_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_string(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_string_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_binary(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_list_u8_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_clock(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_bool_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

/* ── All other typed setters — not supported ─────────────────────────────── */

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_float32(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_f32_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_int8(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_s8_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_int16(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_s16_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_int32(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_s32_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_int64(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_s64_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_uint8(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_u8_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_uint16(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_u16_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_uint32(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_u32_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_uint64(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_u64_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_boolean(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_bool_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_string(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_string_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_binary(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_list_u8_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_clock(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs, co_simulation_fmu_list_bool_t *values)
{ (void)self;(void)vrs;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

/* ═══════════════════════════════════════════════════════════════════════════
 * co-simulation interface — variable dependencies
 * ═══════════════════════════════════════════════════════════════════════════ */

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_number_of_variable_dependencies(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    exports_fmi_fmi3_co_simulation_value_reference_t vr,
    uint64_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{
    (void)self;
    if (vr == VR_OUTPUT_SUM) { *ret = 2; return true; }
    *err = FMI_FMI3_TYPES_STATUS_ERROR;
    return false;
}

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_variable_dependencies(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    exports_fmi_fmi3_co_simulation_value_reference_t dependent,
    exports_fmi_fmi3_co_simulation_list_variable_dependency_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{
    (void)self;
    if (dependent != VR_OUTPUT_SUM) {
        *err = FMI_FMI3_TYPES_STATUS_ERROR;
        return false;
    }

    exports_fmi_fmi3_co_simulation_variable_dependency_t *deps =
        (exports_fmi_fmi3_co_simulation_variable_dependency_t *)
        malloc(2 * sizeof(exports_fmi_fmi3_co_simulation_variable_dependency_t));
    if (!deps) { *err = FMI_FMI3_TYPES_STATUS_ERROR; return false; }

    deps[0].dependent_value_reference    = VR_OUTPUT_SUM;
    deps[0].element_index_of_dependent   = 0;
    deps[0].independent_value_reference  = VR_INPUT_A;
    deps[0].element_index_of_independent = 0;
    deps[0].kind                         = FMI_FMI3_TYPES_DEPENDENCY_KIND_DEPENDENT;

    deps[1].dependent_value_reference    = VR_OUTPUT_SUM;
    deps[1].element_index_of_dependent   = 0;
    deps[1].independent_value_reference  = VR_INPUT_B;
    deps[1].element_index_of_independent = 0;
    deps[1].kind                         = FMI_FMI3_TYPES_DEPENDENCY_KIND_DEPENDENT;

    ret->ptr = deps;
    ret->len = 2;
    return true;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * co-simulation interface — FMU state serialisation
 * ═══════════════════════════════════════════════════════════════════════════ */

/*
 * State layout (33 bytes):
 *   [0]      : in_initialization_mode (1 = true)
 *   [1..8]   : current_time  (f64 little-endian)
 *   [9..16]  : input_a       (f64 little-endian)
 *   [17..24] : input_b       (f64 little-endian)
 *   [25..32] : output_sum    (f64 little-endian)
 */
#define FMU_STATE_SIZE (1 + 4 * 8)

static void write_f64_le(uint8_t *dst, double v)
{
    uint64_t bits;
    memcpy(&bits, &v, sizeof(bits));
    dst[0] = (uint8_t)(bits);
    dst[1] = (uint8_t)(bits >> 8);
    dst[2] = (uint8_t)(bits >> 16);
    dst[3] = (uint8_t)(bits >> 24);
    dst[4] = (uint8_t)(bits >> 32);
    dst[5] = (uint8_t)(bits >> 40);
    dst[6] = (uint8_t)(bits >> 48);
    dst[7] = (uint8_t)(bits >> 56);
}

static double read_f64_le(const uint8_t *src)
{
    uint64_t bits =
        (uint64_t)src[0]        |
        ((uint64_t)src[1] << 8) |
        ((uint64_t)src[2] << 16)|
        ((uint64_t)src[3] << 24)|
        ((uint64_t)src[4] << 32)|
        ((uint64_t)src[5] << 40)|
        ((uint64_t)src[6] << 48)|
        ((uint64_t)src[7] << 56);
    double v;
    memcpy(&v, &bits, sizeof(v));
    return v;
}

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_fmu_state(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    exports_fmi_fmi3_co_simulation_fmu_state_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{
    uint8_t *buf = (uint8_t *)malloc(FMU_STATE_SIZE);
    if (!buf) { *err = FMI_FMI3_TYPES_STATUS_ERROR; return false; }

    buf[0] = self->in_initialization_mode ? 1u : 0u;
    write_f64_le(buf + 1,  self->current_time);
    write_f64_le(buf + 9,  self->input_a);
    write_f64_le(buf + 17, self->input_b);
    write_f64_le(buf + 25, self->output_sum);

    ret->ptr = buf;
    ret->len = FMU_STATE_SIZE;
    return true;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_fmu_state(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    exports_fmi_fmi3_co_simulation_fmu_state_t *state)
{
    if (state->len < FMU_STATE_SIZE) return FMI_FMI3_TYPES_STATUS_ERROR;
    const uint8_t *b = state->ptr;
    self->in_initialization_mode = (b[0] != 0);
    self->current_time = read_f64_le(b + 1);
    self->input_a      = read_f64_le(b + 9);
    self->input_b      = read_f64_le(b + 17);
    self->output_sum   = read_f64_le(b + 25);
    return FMI_FMI3_TYPES_STATUS_OK;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * co-simulation interface — directional / adjoint derivatives
 * ═══════════════════════════════════════════════════════════════════════════ */

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_directional_derivative(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *unknowns,
    co_simulation_fmu_list_value_reference_t *knowns,
    co_simulation_fmu_list_f64_t *seed,
    co_simulation_fmu_list_f64_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{
    (void)self;
    /* Only supports unknowns = [VR_OUTPUT_SUM]. */
    if (unknowns->len != 1 || unknowns->ptr[0] != VR_OUTPUT_SUM) {
        *err = FMI_FMI3_TYPES_STATUS_ERROR;
        return false;
    }
    double sensitivity = 0.0;
    for (size_t i = 0; i < knowns->len; i++) {
        uint32_t vr = knowns->ptr[i];
        if (vr == VR_INPUT_A || vr == VR_INPUT_B) {
            sensitivity += (i < seed->len) ? seed->ptr[i] : 0.0;
        }
    }
    double *buf = (double *)malloc(sizeof(double));
    if (!buf) { *err = FMI_FMI3_TYPES_STATUS_ERROR; return false; }
    buf[0] = sensitivity;
    ret->ptr = buf;
    ret->len = 1;
    return true;
}

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_adjoint_derivative(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *unknowns,
    co_simulation_fmu_list_value_reference_t *knowns,
    co_simulation_fmu_list_f64_t *seed,
    co_simulation_fmu_list_f64_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{
    (void)self;
    if (unknowns->len != 1 || unknowns->ptr[0] != VR_OUTPUT_SUM) {
        *err = FMI_FMI3_TYPES_STATUS_ERROR;
        return false;
    }
    double s = (seed->len > 0) ? seed->ptr[0] : 0.0;
    size_t n = knowns->len;
    double *buf = (double *)malloc(n * sizeof(double));
    if (!buf) { *err = FMI_FMI3_TYPES_STATUS_ERROR; return false; }
    for (size_t i = 0; i < n; i++) {
        uint32_t vr = knowns->ptr[i];
        buf[i] = (vr == VR_INPUT_A || vr == VR_INPUT_B) ? s : 0.0;
    }
    ret->ptr = buf;
    ret->len = n;
    return true;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * co-simulation interface — clock interval / shift (not supported)
 * ═══════════════════════════════════════════════════════════════════════════ */

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_interval_decimal(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs,
    exports_fmi_fmi3_co_simulation_list_tuple2_f64_interval_qualifier_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_interval_fraction(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs,
    exports_fmi_fmi3_co_simulation_list_tuple2_interval_fraction_interval_qualifier_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_shift_decimal(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs,
    co_simulation_fmu_list_f64_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_shift_fraction(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs,
    exports_fmi_fmi3_co_simulation_list_interval_fraction_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)vrs;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_interval_decimal(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs,
    co_simulation_fmu_list_f64_t *intervals)
{ (void)self;(void)vrs;(void)intervals; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_interval_fraction(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs,
    exports_fmi_fmi3_co_simulation_list_interval_fraction_t *intervals)
{ (void)self;(void)vrs;(void)intervals; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_shift_decimal(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs,
    co_simulation_fmu_list_f64_t *shifts)
{ (void)self;(void)vrs;(void)shifts; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_shift_fraction(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_value_reference_t *vrs,
    exports_fmi_fmi3_co_simulation_list_interval_fraction_t *shifts)
{ (void)self;(void)vrs;(void)shifts; return FMI_FMI3_TYPES_STATUS_ERROR; }

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_evaluate_discrete_states(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self)
{ (void)self; return FMI_FMI3_TYPES_STATUS_ERROR; }

/* ═══════════════════════════════════════════════════════════════════════════
 * co-simulation interface — Co-Simulation-specific methods
 * ═══════════════════════════════════════════════════════════════════════════ */

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_set_input_derivatives(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_tuple2_value_reference_u32_t *requests,
    co_simulation_fmu_list_f64_t *values)
{ (void)self;(void)requests;(void)values; return FMI_FMI3_TYPES_STATUS_ERROR; }

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_get_output_derivatives(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    co_simulation_fmu_list_tuple2_value_reference_u32_t *requests,
    co_simulation_fmu_list_f64_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{ (void)self;(void)requests;(void)ret; *err=FMI_FMI3_TYPES_STATUS_ERROR; return false; }

bool
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_do_step(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self,
    double current_communication_point,
    double communication_step_size,
    bool   no_set_fmu_state_prior_to_current_point,
    exports_fmi_fmi3_co_simulation_do_step_result_t *ret,
    exports_fmi_fmi3_co_simulation_status_t *err)
{
    (void)no_set_fmu_state_prior_to_current_point;
    double next_time = current_communication_point + communication_step_size;
    self->current_time = next_time;
    self->output_sum   = self->input_a + self->input_b;
    ret->last_successful_time = next_time;
    ret->event_handling_needed = false;
    ret->terminate_simulation  = false;
    ret->early_return          = false;
    (void)err;
    return true;
}

exports_fmi_fmi3_co_simulation_status_t
exports_fmi_fmi3_co_simulation_method_co_simulation_instance_enter_step_mode(
    exports_fmi_fmi3_co_simulation_borrow_co_simulation_instance_t self)
{ (void)self; return FMI_FMI3_TYPES_STATUS_ERROR; }
